openapi: 3.1.0
servers: [url: https://localhost:8904]
security: [ ]

x-shared-blocks:
  this_key_irrelevant: &title_block
    title: YAML merge keys are working
  this_key_also_irrelevant: &version_block
    version: "2.0"

  irrelevant5: &merged_node
    description: If you can see this, the parser handles merge keys.

  irrelevant4: &another_node
    description: Referenced using a regular (non-merge) alias.

    
info:
  description: |
    OpenAPI's YAML parser does not support [Merge keys](https://yaml.org/type/merge.html).  If merge
    keys are working this section will have the title "YAML merge keys are working" and will be
    version 2.0.
  <<: [*title_block, *version_block]

paths:
  /api:
    get:
      summary: Sample path
      description:  Choose a response.  If the 400 responses show a description, the YAML parser supports merge keys.
      responses:
        # redoc requires numeric keys here.
        200: *another_node
        400:
          <<: *merged_node
        404:
          <<: *merged_node
        
