openapi: 3.1.0
servers: [url: https://localhost:8904]
security: [ ]

info:
  version: "1"
  title: Checking allOf and oneOf
  description: |
    Testing handling of `allOf` and `oneOf`.  Go to the "Look at me!" path.

components:
  schemas:
    simple1:
      title: Simple schema one title
      description:  Simple schema one description
      type: object
      properties:
        firstObjectField1:
          type: string
          example: firstObjectField1 example
        firstObjectField2:
          type: string
          example: firstObjectField2 example

    simple2:
      title: Simple schema two title
      description:  Simple schema two description
      type: object
      properties:
        secondObjectField1:
          type: string
          example: secondObjectField1 example
        secondObjectField2:
          type: string
          example: secondObjectField2 example

    usesAllOf:
      title: Uses allOf title
      description: uses `allOf` description
      allOf:
        - type: object
          description: desc of first allOf object
          properties:
            firstObjectField1:
              type: string
              example: firstObjectField1 example
            firstObjectField2:
              type: string
              example: firstObjectField2 example
        - type: object
          description: "desc of second allOf object.  RapiDoc shows it (go RapiDoc!)"
          properties:
            secondObjectField1:
              type: string
              example: secondObjectField1 example
            secondObjectField2:
              type: string
              example: secondObjectField2 example

    usesOneOf:
      title: Uses oneOf title
      description: uses `oneOf` description
      oneOf:
        - type: object
          description: desc1
          title: title1
          summary: summary1
          properties:
            firstObjectField1:
              type: string
              example: firstObjectField1 example
            firstObjectField2:
              type: string
              example: firstObjectField2 example
        - type: object
          description: "desc of second oneOf object.  RapiDoc shows it (go RapiDoc!)"
          properties:
            secondObjectField1:
              type: string
              example: secondObjectField1 example
            secondObjectField2:
              type: string
              example: secondObjectField2 example

    
paths:
  /api:
    get:
      summary: Look at me!
      description: |
          Responses 200, 202, and 204 should appear the same.  Responses 201, 203, and 205 should
          appear the same.

      responses:
        "200":
          description: Uses `allOf` on in-line schemas.
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    description: desc of first allOf object
                    properties:
                      firstObjectField1:
                        type: string
                        example: firstObjectField1 example
                      firstObjectField2:
                        type: string
                        example: firstObjectField2 example
                  - type: object
                    description: desc of second allOf object
                    properties:
                      secondObjectField1:
                        type: string
                        example: secondObjectField1 example
                      secondObjectField2:
                        type: string
                        example: secondObjectField2 example

        "201":
          description: Uses `OneOf` with all schemas inlined
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    description: desc1
                    # OpenAPI Explorer shows the object's title.  No default.  Picker always uses "Example-n".
                    # Redoc uses the title in its picker.  Default is the object's type (probably "object")
                    # RapiDoc uses the title in its picker.  Default is "Example n".

                    # Scalar is like Redoc:  "title1" for the first and "object" for the second.
                    # Its example only shows the first option:  you cannot see an example of the
                    # second option.

                    # Zudoku is like Redoc except "title1" for the first and an auto-generated
                    # "Variant 2" for the second.  It also only shows the first option as an
                    # example.
                    
                    title: title1
                    summary: summary1
                    properties:
                      firstObjectField1:
                        type: string
                        example: firstObjectField1 example
                      firstObjectField2:
                        type: string
                        example: firstObjectField2 example
                  - type: object
                    description: desc2
                    properties:
                      secondObjectField1:
                        type: string
                        example: secondObjectField1 example
                      secondObjectField2:
                        type: string
                        example: secondObjectField2 example

        "202":
          description: Uses `allOf` to references.  Should be identical to 200.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/simple1"
                  - $ref: "#/components/schemas/simple2"

        "203":
          description: Uses `oneOf` to references.  Should be identical to 201.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/simple1"
                  - $ref: "#/components/schemas/simple2"

        "204":
          description: Uses a reference to a schema that uses `allOf`
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usesAllOf"

        "205":
          description: Uses a reference to a schema that uses `oneOf`
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usesOneOf"

        "299":
          description: "No composition, just simple fields"
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstObjectField1:
                    type: string
                    example: firstObjectField1 example
                  firstObjectField2:
                    type: string
                    example: firstObjectField2 example


